config/routes.rb
Rails.application.routes.draw do
  # Campaign Routes
  resources :campaigns
  # Root Url
  root :to => 'index#index'
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = Campaign.all
  end

  def new
    @campaign = Campaign.new
  end

  def edit
    @campaign = Campaign.find(params[:id])    
  end

  def update
    @campaign = Campaign.find(params[:id])

    if @campaign.update_attributes(campaign_params)
      flash[:notice] = "Campaign was updated."
      redirect_to campaigns_path
    else
      flash[:error] = "There was an error updating the campaign. Please try again."
      render :edit
    end    
  end

  def create
    @campaign = Campaign.new(campaign_params)    

    if @campaign.save
      flash[:notice] = "Campaign was saved."
      redirect_to campaigns_path
    else
      flash[:error] = "There was an error saving the campaign. Please try again."
      render :new
    end    
  end

  def destroy
    @campaign = Campaign.find(params[:id])
    title = @campaign.title

    if @campaign.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @campaign
    else
      flash[:error] = "There was an error deleting the campaign. Please try again."
      render :show
    end    
  end

  def show
    @campaign = Campaign.find(params[:id])
  end

  private

  def campaign_params
    params.require(:campaign).permit(:title)
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/campaigns/_form.html.erb
<%= simple_form_for @campaign do |f| %>
  <%= f.input :title, label: 'Title', placeholder: "Enter list title" %>
  <%= f.submit 'Save' , class: 'btn btn-success' %>
<% end %>

app/views/campaigns/edit.html.erb
<%= render partial: 'campaigns/form' %>

app/views/campaigns/index.html.erb
<% @campaigns.each do |campaign| %>
	<%= link_to campaign.title, campaign_path(campaign) %><br>
<% end %>
<%= link_to "Create a New Campaign", new_campaign_path ,class: 'btn btn-success' %>

app/views/campaigns/new.html.erb
<%= render partial: 'campaigns/form' %>

app/views/campaigns/show.html.erb
<%= @campaign.title %>
<%= link_to "Edit", edit_campaign_path ,class: 'btn btn-success' %>
<%= link_to "Delete", @campaign ,class: 'btn btn-danger', method: :delete %>

app/views/index/index.html.erb
This is the homepage!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rdugc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- FLASH MESSAGES -->
	<% if flash[:notice] %>
		<div class="alert alert-success">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:notice] %>
		</div>
	<% elsif flash[:error] %>
		<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:error] %>
		</div>
	<% elsif flash[:alert] %>
		<div class="alert alert-warning">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:alert] %>
		</div>
	<% end %>
	<!-- END FLASH MESSAGES -->
	<%= yield %>
</body>
</html>